theme: jekyll-theme-primer
title: Movie Map
description: Movie Map is a handy Alexa skill that helps you find where to stream, rent, or buy movies in your country without needing to browse or search for it.
exclude: ['LISTING.md']
